### ISSUE TITLE
create a improved installer

### ISSUE THREAD

**Issue by mathzds** [System64fumo/sysbar#3]
make some easiest installer for another distros

**Comment by System64fumo** [comment]
`make install` should work on all distros?
I think you mean create a package for other distros?

My programs are available on the AUR (Packaged by me) since i use Artix linux, Some packages are available on NIX (Packaged by random individuals)
I can't maintain packages on other distros nor can i be bothered to package them myself.
I have no issue with people packaging my software though so if you're interested feel free to do so!

I am however down to help any issues that prevent my software from being installed on other distros.
